### ISSUE TITLE
Version 0.2.1.0

### ISSUE THREAD

**Issue by MichaelHin** [chaos-chat/chaos-chat.client#1]
Mit "2" als Eingabe wird nicht eine Message an die selbe Person geschrieben, sondern man muss den Chat noch auswählen. 
![fehler_auswahl](https://user-images.githubusercontent.com/38217878/116908866-b090d480-ac43-11eb-8046-369fd035def0.PNG)

**Comment by clucht** [comment]
resolved in version 0.3.1
