### ISSUE TITLE
Fehler Chat mit Dummy User

### ISSUE THREAD

**Issue by MichaelHin** [chaos-chat/chaos-chat.client#6]
Fehler beim Schreiben des Text "test2" an den Dummy User. Der Fehler ist nicht wiederholbar, nach einem Neustart der Applikation konnte test2 ohne Probleme geschrieben werden. 
![fehler_chat_mit_dummy](https://user-images.githubusercontent.com/38217878/123535277-0d2fdd80-d723-11eb-909c-7469d690e45f.PNG)

**Comment by clucht** [comment]
Der Fehler tritt durch die in dieser Version nicht abgefangenen Backspace im Inputsystem auf und wurde in der neuen Version bereits gefixt. Deshalb sollte dieses Verhalten in der neuen Version erneut geprüft werden.
